name: Actualizare Zilnica Meteo

on:
  schedule:
    - cron: '0 3 * * *' # Rulează în fiecare noapte la ora 03:00 (ora RO)
  workflow_dispatch: # Permite și pornirea manuală din tab-ul Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cod
        uses: actions/checkout@v3

      - name: Setare Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalare dependinte
        run: |
          pip install pandas requests streamlit plotly

      - name: Executie script extragere
        run: python app.py --update_only

      - name: Salvare date noi in GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Verificăm dacă fișierul a fost creat/modificat înainte de commit
          git add baza_date.csv
          git commit -m "Actualizare automata date meteo [skip ci]" || exit 0
          git push
